# Generated by Django 4.0.5 on 2022-10-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0006_contectus_jobapplication_apply_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="experience_requride",
            new_name="experience_required",
        ),
    ]
