# Generated by Django 4.0.5 on 2022-10-28 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0008_job_posted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="contectus",
            name="contact_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
